### ISSUE TITLE
Curl dependency

### ISSUE THREAD

**Issue by evg82** [krupakov/telegrab#1]
Hi, your libs looks perfect for low resource machine, im working in a project (openZmeter) where a telegram lib is needed to work in a low end ARM SOC. We use the nlohmann lib yet. However we stop using curl some time and replace it with another "single file" HTTP client/server lib (cpp-httplib).

This HTTP lib is in C++. I think in fork your project and replace the curl calls with cpp-httplib, but i think is better to ask you before, maybe you are interested in this change and we can supply a pull request instead of create a new derived lib.

**Comment by krupakov** [comment]
It would be great. I personally prefer single file libs, it is unfortunate that I haven't heard about this one before.
